### ISSUE TITLE
Whether it works in Chinese Word Segmentation

### ISSUE THREAD

**Issue by hzylmf** [LiyuanLucasLiu/LM-LSTM-CRF#17]
Thank for your code. I wanna use this code for Chinese Word Segmentation, so does it work for applying the code to my word segmentation task?

**Comment by LiyuanLucasLiu** [comment]
Thanks:-)

The current code cannot work for Chinese, but you can definitely modified it a little to make it work on Chinese. 

Basically, i would recommended you to use our word-level model, treat each Chinese character as a word, and modify the encoding for read & write. Also, pre-trained embeddings are crucial for performance, i would also recommend you to get some character-level embedding for Chinese (there are several papers about this). 

Besides, you could also try to represent Chinese Characters by Wubi or Pingying, and treat them as character-level representation.
