### ISSUE TITLE
rand_init_hidden() for lstm

### ISSUE THREAD

**Issue by jiesutd** [LiyuanLucasLiu/LM-LSTM-CRF#18]
Hi Liyuan,

I am writing my own lstm-crf model for ner. My model works well except a slight memory leak (on CPU memory). 
After debugging, I found the memory leak is caused by the lstm layer. I doubt it's caused by the hidden state initialization (although I followed the tutorial). 

I checked your code ``train_w.py`` and ``lstm_crf.py``, and found that you defined the ``rand_init_hidden()`` function to initialize the hidden state of lstm, but I can't find the place you use this function. Maybe I missed some important part. 
Could you please tell me how do you initialize your hidden state of lstm ? 

Thank you very much!

**Comment by LiyuanLucasLiu** [comment]
Hi, thanks for asking.
Yes, the ```rand_init_hidden()``` is not used. By default, the hidden state would be initialized to zero (https://discuss.pytorch.org/t/when-to-initialize-lstm-hidden-state/2323). We found this strategy works well, and havn't try the ```rand_init_hidden()``` method in our experiments.
