### ISSUE TITLE
Scores, Batching and learning rate

### ISSUE THREAD

**Issue by ngarneau** [LiyuanLucasLiu/LM-LSTM-CRF#23]
Hey guys,
Thanks for releasing your code I am inspiring myself a lot from it by building a custom NER model.
I have an open question about the scores, batching and the learning rate.

I did some experimentation with different batch sizes/learning rates with my own data (even with other NER model based on a CRF) and I found out that:

Increasing the batch size (and averaging the scores) without increasing the learning makes the model learns really poorly / slowly. On the other end, when I sum the scores, then the model converges as expected. Say going from batch size = 1 to 16, learning rate at 0.005.

Increasing the batch size (and averaging the scores) **and** increasing the learning rate makes the model converge as expected. Say going from batch size = 1 to 16 and learning rate from 0.005 to 0.01.

It seems to me that averaging the scores of the sentences within a batch makes the model learn a lot more slowly. I want to know if you did the same experimentation with another dataset and you got the same behaviour as the one that I have here with the model. I'm also curious to know what is the intuition behind this behaviour.

Many thanks,

Nicolas

**Comment by LiyuanLucasLiu** [comment]
Hi Nicolas, thanks for asking :-)

I haven't try different batch size. But your observation seems reasonable for me.

Let's say the corpus has 1000 instances and the loss is averaged across the batch. If the batch size is set to 10, there would be 100 updates in each epoch, after which there would be a reduce of learning rate. If the batch size is set to 50, there would be 20 updates in each epoch, after which there would be a reduce of learning rate. So, increasing the batch size from 10 to 50, would make the total update value (for each epoch) 5 times smaller (in expectation and to some extend). Accordingly, you may need to increase the learning rate and batch size at the same time (or reduce the speed of decreasing learning rate).

Best,
Lucas
