### ISSUE TITLE
evaluator eval_batch.f1_score has inconsistent return types

### ISSUE THREAD

**Issue by napsternxg** [LiyuanLucasLiu/LM-LSTM-CRF#3]
When I try to run the NER script with eva_matrix as `fa`, then I get the following error on Line 207:
`TypeError: FloatType cannot be iterated`

This happens because the f1_score function returns a single value in some cases when it should be returning 4 values. This should need a minor fix.

**Comment by LiyuanLucasLiu** [comment]
Thanks a lot for the fix!
