### ISSUE TITLE
Could you specify the version of the Torch and Python

### ISSUE THREAD

**Issue by xiaoleihuang** [LiyuanLucasLiu/LM-LSTM-CRF#33]
Currently I successfully finished running the experiments, but I found there are several key requirements of running platform:
1. The current code works well with Torch upper to 0.3;
2. The binary Torch installation file should be specified to the cuda version & python version as well.

**Comment by LiyuanLucasLiu** [comment]
thx, i've updated the ReadMe for the pytorch version requirement
