### ISSUE TITLE
LM-LSTM-CRF training performance 

### ISSUE THREAD

**Issue by hukai-sun** [LiyuanLucasLiu/LM-LSTM-CRF#42]
Hello,thank for your good job.

But when i use your train_wc.py code to train your model on CONll2003 NER dataset , i just get such result : test f1 score 91.14 ,which is different with the result in your paper. The hyperparameters are the same with your suggestions.
So , why?
Maybe i have not taken something into consideration.

Thank for your help.

**Comment by LiyuanLucasLiu** [comment]
Hi, thanks for asking. Due to a bug found in the old implementation, the results reported in the paper can not be directly compared with other papers' result (but the comparison among method 12/13/14/15 is still valid). The comparable results are updated in the readme file, which is 91.24+/-0.12.
