### ISSUE TITLE
Mismatch of performance between this repository and the paper

### ISSUE THREAD

**Issue by jind11** [LiyuanLucasLiu/LM-LSTM-CRF#44]
hi, I have carefully read your paper and this repository, but I found the claimed mean and max F1 scores for NER are different between the paper and this repository, is there any reason behind? Thanks!

**Comment by LiyuanLucasLiu** [comment]
Hi, thanks for asking. Due to a bug found in the old implementation, the results reported in the paper can not be directly compared with other papers' result (but the comparison among methods 12/13/14/15 is still valid, since they are evaluated with the same script). The comparable results are updated in the readme file, which is 91.24+/-0.12.

**Comment by jind11** [comment]
So you mean the reported scores in the paper are indeed not valid caused by a bug in the code?

**Comment by LiyuanLucasLiu** [comment]
The reported performance of the POS-tagging is valid, but the reported F1 scores are not precise (pls refer to the reported number in the ReadMe file as more accurate results).

**Comment by LiyuanLucasLiu** [comment]
I will modify the ReadMe file and highlight this information.

**Comment by jind11** [comment]
I see, could you kindly explain the bug causing this issue? I thought using the official scorer to compute the F1 score for NER should be 100% safe, isn't it? I want to make sure that my computed score using the official scorer is accurate. Many thanks!

**Comment by LiyuanLucasLiu** [comment]
Yes, the official scorer is accurate. 

As to the bug, we re-implemented that script with python for better efficiency (the decode speed of the best model in our recent work is 156K words/sec, https://github.com/LiyuanLucasLiu/LD-Net). However, an ```elif``` is accidentally modified as ```if``` during the implementation refactoring.
