### ISSUE TITLE
evaluator.calc_score

### ISSUE THREAD

**Issue by yael432** [LiyuanLucasLiu/LM-LSTM-CRF#47]
The 'evaluator.calc_score' function can return two types of objects: dictionary and tuple
Can raise an error in train_wc line 222

**Comment by LiyuanLucasLiu** [comment]
emm, but only when the evaluate_metric is f, it would enter the line 222. Can you provide more details about this issue ?

**Comment by yael432** [comment]
See f1_score function in evaluator.py, theoretically one of the preconditions could be equal to zero.

**Comment by LiyuanLucasLiu** [comment]
Thanks a lot! Nice catch :-) 
Fixed via #48
