### ISSUE TITLE
KeyError in predictor.py class predict

### ISSUE THREAD

**Issue by yael432** [LiyuanLucasLiu/LM-LSTM-CRF#51]
line: 59        

 for f, y in zip(feature, label):
                label = self.r_l_map[y]

label parameter passed from seq_wc is a tensor type, therefore self.r_l_map[y] raise a KeyError

I guess it should be  label = self.r_l_map[y.item()] instead?

**Comment by LiyuanLucasLiu** [comment]
Thanks and fixed! Nice catch :-) #52 
BTW, you may want to check our new implementation w. more powerful pre-trained models.
https://github.com/LiyuanLucasLiu/LightNER
