### ISSUE TITLE
Incorrect Precision Output for test_rec

### ISSUE THREAD

**Issue by w1nd3x** [LiyuanLucasLiu/LM-LSTM-CRF#70]
In train_wc.py line 224 test_rec and test_pre are switched in the assignment statement.  This leads to the final precision and recall being backward when the model finishes training and outputs the final results.  Order should be the same as line 215 for the dev set results.
line 224: (test_f1, test_rec, test_pre, test_acc, msg) = test_result['total']

**Comment by LiyuanLucasLiu** [comment]
nice catch and fixed. BTW, this repo is out-dated, you may want to check https://github.com/LiyuanLucasLiu/Vanilla_NER
