### ISSUE TITLE
Line 530 in utils.py is too slow with huge datasets

### ISSUE THREAD

**Issue by andreybondarb** [LiyuanLucasLiu/LM-LSTM-CRF#71]
Line 530 in **construct_bucket_vb_wc** function in **utils.py** is too slow with huge datasets. It even freezes if dataset is larger than 300k objects.

I propose to change line

`forw_corpus = [pad_char_feature] + list(reduce(lambda x, y: x + [pad_char_feature] + y, forw_features)) + [pad_char_feature]`

to

```
forw_corpus = [pad_char_feature]
for forw_feature in forw_features:
   forw_corpus.extend(forw_feature + [pad_char_feature])
```

Which works considerably faster with no freezes.

**Comment by LiyuanLucasLiu** [comment]
thanks and fixed in https://github.com/LiyuanLucasLiu/LM-LSTM-CRF/commit/4f35e0a18ade83ee46718a3a8b4f6f0790f9da58
PS: a more up-to-date lib is available at https://github.com/LiyuanLucasLiu/Vanilla_NER
